version: "3.9"

services:

  postgres:
    volumes:
      - /opt/gridwar/pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

  backend:
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod

  frontend:
    restart: unless-stopped
